Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Control (master node)
  config.vm.define "control" do |node|
    node.vm.hostname = "control"
    node.vm.network "private_network", ip: "192.168.56.1"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end
  end

  # Server 1
  config.vm.define "server-1" do |node|
    node.vm.hostname = "server-1"
    node.vm.network "private_network", ip: "192.168.56.2"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
  end

  # Server 2
  config.vm.define "server-2" do |node|
    node.vm.hostname = "server-2"
    node.vm.network "private_network", ip: "192.168.56.3"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
  end

  # Worker 1
  config.vm.define "worker-1" do |node|
    node.vm.hostname = "worker-1"
    node.vm.network "private_network", ip: "192.168.56.4"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end
  end

  # Worker 2
  config.vm.define "worker-2" do |node|
    node.vm.hostname = "worker-2"
    node.vm.network "private_network", ip: "192.168.56.5"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end
  end

  # CICD
  config.vm.define "cicd" do |node|
    node.vm.hostname = "cicd"
    node.vm.network "private_network", ip: "192.168.56.6"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end
  end

  # Monitoring
  config.vm.define "monitoring" do |node|
    node.vm.hostname = "monitoring"
    node.vm.network "private_network", ip: "192.168.56.7"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end
  end

  # NFS
  config.vm.define "nfs" do |node|
    node.vm.hostname = "nfs"
    node.vm.network "private_network", ip: "192.168.56.8"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  # ArgoCD
  config.vm.define "argocd" do |node|
    node.vm.hostname = "argocd"
    node.vm.network "private_network", ip: "192.168.56.9"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end
  end
end
