apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      # 🧭 Force le déploiement sur la VM monitoring
      nodeSelector:
        kubernetes.io/hostname: monitoring

      containers:
        - name: prometheus
          image: prom/prometheus:v2.55.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9090
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

          # 🧱 Montage des volumes
          volumeMounts:
            - name: prometheus-storage
              mountPath: /prometheus
            - name: prometheus-config
              mountPath: /etc/prometheus

      # 🔗 Définition des volumes persistants et de config
      volumes:
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc   # ⚠️ ton PVC déjà créé
        - name: prometheus-config
          configMap:
            name: prometheus-config     # ⚠️ ta ConfigMap prometheus.yml

