---
apiVersion: v1  
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: 30900
